[dependencies]
base = "0.13.5"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
itertools = "0.1.1"

[package]
name = "helion-dao"
version = "0.0.1"
description = "A full implementation of the ICRC-1 fungible token standard for the Helion AI DAO"
repository = "https://github.com/helionicp/helion-dao"
keywords = ["icrc1", "fungible", "token", "standard", "dfinity", "helion-dao"]
